### ISSUE TITLE
Expose client IP as a property

### ISSUE THREAD

**Issue by AudioW** [adzialocha/osc-js#10]
Is it possible to retrieve the IP address that a client is connected to after it is initialized?

**Comment by adzialocha** [comment]
It depends which protocol you are using? UDP? WebSocket? There is ways to figure that out, but I dont see this being a feature of this library since it is not needed for OSC communication. You might want to write your own plugin for this https://github.com/adzialocha/osc-js/wiki/Plugin-API

**Comment by AudioW** [comment]
Check
