### ISSUE TITLE
Ionic 3 CORS issue

### ISSUE THREAD

**Issue by AudioW** [adzialocha/osc-js#12]
Hi,

I am trying to get this great package into Ionic 3 (only websocket client support I guess?)

I set up a websocket client like the example:

`var websocketClient = new OSC({plugin: new OSC.WebsocketClientPlugin({host: address', port:9011})});`

When running this on the ios simulator I get a cors issue:

> Origin http://192.168.1.247:8100 is not allowed by Access-Control-Allow-Origin.

I tried setting a proxy which is recommended by ionic but this doesn't fix the problem

Any ideas?

**Comment by adzialocha** [comment]
CORS issues are not really related to this library, maybe this helps though: http://blog.ionic.io/handling-cors-issues-in-ionic/
