### ISSUE TITLE
Pass client when Websocket Server receives Message

### ISSUE THREAD

**Issue by AudioW** [adzialocha/osc-js#13]
Hi,

I am trying to find out which websocket client send a message to the WebSocket Server but the 'message' event only passes the received message. Is it possible to add the client to the message event handler so you can see who send it and easily send a message back from the server to the client?

Thanks

**Comment by adzialocha** [comment]
Information about clients etc. relies on the actual project and is not necessarily a part of the library. I suggest you add the needed information in the arguments of your osc message
