### ISSUE TITLE
TypeError: OSC.WebsocketClientPlugin is not a constructor

### ISSUE THREAD

**Issue by rm8x** [adzialocha/osc-js#24]
Greetings!

I'm using this fine work as a dependency in [an A-Frame component](https://github.com/rm8x/aframe-oscsend-component) and am running into this error using the browser files of the current release.  This code results in the error: ```    var plugin = new OSC.WebsocketClientPlugin({host: this.data.serverURL, port: this.data.serverPort });```

 Since WebSocketClientPlugin is the default I can work around this like so:  ``` osc = new OSC();
 osc.open({host: this.data.serverURL, port: this.data.serverPort });```

**Comment by adzialocha** [comment]
Thank you @rm8x!

What error does occur? I can't reproduce the problem, this here does not throw any errors in version `1.2.0`:

```js
const OSC = require('osc-js')

var plugin = new OSC.WebsocketClientPlugin({
  host: 'localhost',
  port: 44121,
})

const osc = new OSC({
  plugin,
})
```

**Comment by jarmitage** [comment]
I have this error also when using the example here https://github.com/adzialocha/osc-js/wiki/Node.js-Server#websocket-server-example

**Comment by adzialocha** [comment]
@jarmitage Are you sure you are using the right plugins? When working with the only browser version (for Webpack builds for exampe), the plugin is called `WebsocketBrowserPlugin` (which is also set by default), when working with the normal version it is `WebsocketClientPlugin`.

Example using the browser version:

```
var osc = new OSC();

var plugin = new OSC.WebsocketBrowserPlugin({
  host: 'localhost',
  port: 44121,
})

osc.open({ port: 9912, plugin });
```

**Comment by adzialocha** [comment]
I updated the Wiki (https://github.com/adzialocha/osc-js/wiki/Webpack-Bundling), maybe this point was too confusing before

**Comment by jarmitage** [comment]
I get the same error (`OSC.DatagramPlugin is not a constructor`) when trying to run the UDP example (https://github.com/adzialocha/osc-js/wiki/Node.js-Server#udp-server-example)

I'm trying to do something equivalent to this: https://github.com/colinbdclark/osc.js-examples/tree/master/browser

**Comment by adzialocha** [comment]
@jarmitage as long as you are using the browser version this wont work either. Please use the normal osc-js version if you want to work with UDP.

If the problem still occurs I would need more information to really help you

**Comment by gilfuser** [comment]
Hi.
I'm getting similar erros as the described above. I'm going to give the information I think would be useful. Please tell me if there is something missing or if I can help somehow.

My particular case is an application made with Vue/Nuxt + express, and I'm following the osc-js-webpack-example.
I got errors both in the server and client sides.

In the client the error is this:
```
{ TypeError: __WEBPACK_IMPORTED_MODULE_5_osc_js___default.a is not a constructor
    at VueComponent.data (pages/index.1b33cb139b7bbca63b19.js:113:10)
    ...
``` 
The `VueComponent.data` points to where the `new OSC()` is.
The webpack.config is not exposed in Nuxt, but there is a nuxt.config from which one can configure Webpack, specifically in this part:
```
    extend(config, ctx) {

      config.resolve.alias['osc-js'] = path.resolve(__dirname, 'node_modules/osc-js/lib/osc.browser.js')

      // Run ESLint on save
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/,
        })
      }
    }
```
In the server version I'm getting this error:
```
const osc = new OSC({ plugin: new OSC.WebsocketServerPlugin() })
                               ^
TypeError: OSC.WebsocketServerPlugin is not a constructor
```

My package.json file is like so (thinking about what could be useful to understand what's going on):
```
{
  "name": "deslugar",
  "version": "1.0.0",
  "description": "non-local osc jam",
  "author": "Gil Fuser",
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development nodemon server/index.js --watch server",
    "build": "nuxt build",
    "start": "cross-env NODE_ENV=production nodemon server/index.js",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "dependencies": {
    "@nuxtjs/axios": "^5.0.0",
    "express": "^4.15.3",
    "nuxt": "^1.0.0",
    "osc-js": "^1.2.2",
    "signalhub": "^4.9.0",
    "socket.io": "^2.1.1",
    "socket.io-client": "^2.1.1",
    "webrtc-swarm": "^2.9.0",
    "wrtc": "^0.2.0"
  },
  "devDependencies": {
    "ajv": "^6.5.3",
    "babel-eslint": "^8.2.1",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "cross-env": "^5.0.1",
    "eslint": "^4.19.1",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-vue": "^4.0.0",
    "nodemon": "^1.11.0"
  }
}
```
... and and webpack version 3.12.0

I really like that project and would like to experiment and use osc-js, so, any help would be much appreciated.

best regards,
Gil
