### ISSUE TITLE
WebSocket connection to 'ws://127.0.0.1:57121/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by jarmitage** [adzialocha/osc-js#25]
Hi, thanks for the module!

Trying to run the WebSocket server example code (https://github.com/adzialocha/osc-js/wiki/Node.js-Server#websocket-server-example, with this workaround https://github.com/adzialocha/osc-js/issues/24) in a webpack based project (using the instructions here https://github.com/adzialocha/osc-js/wiki/Webpack-Bundling), but getting `WebSocket connection to 'ws://127.0.0.1:57121/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

No idea why. I have had success with `osc.js` but can't get that to work with webpack so trying to migrate to this library.

Any ideas how to figure out why this connection gets refused?

```
const OSC = require('osc-js')

const osc = new OSC();
osc.open({ host: '127.0.0.1', port: 57121 });

osc.on('/test', (message) => {
  console.log(message.args)
})
```

**Comment by adzialocha** [comment]
Hi @jarmitage! :-) This is hard to tell, since it might also be related to your network configuration and backend. Did you try using ip address `0.0.0.0`?

**Comment by triceratupuz** [comment]
Hi, have same problem with this trivial example:
`<html>
<head>
<meta charset="utf-8">
<script type="text/javascript" src="osc-js-master/dist/osc.min.js"></script>
<script type="text/javascript">
const plugin = new OSC.WebsocketBrowserPlugin({ port: 19912 })
const osc = new OSC(
{
  discardLateMessages: false,
  plugin: plugin
});
osc.open({ host: '127.0.0.1' });
function activator(id) {
	   var message = new OSC.Message('/test/random', Math.random());
		osc.send(message);
}
</script>
	</head>
	<body>
		<input type="button" value="Press Butt1" id="I'm 1" onclick="activator(id)">
	</body>
</html>`

tried also 0.0.0.0 with same results. Is there anything i could check?

**Comment by adzialocha** [comment]
@triceratupuz do you have more information regarding your setup / server implementation?

**Comment by triceratupuz** [comment]
By further reading the docs/examples seems that what i'd like to do is not possible but I'll explain anyhow:
On the same computer I'd like to send messages from the browser (running the script above) to an audio program (csound). I'm currently not using csound but a software to monitor osc messages.
Could you confirm that an additional server is required?

**Comment by adzialocha** [comment]
@triceratupuz in most of the cases you might need a bridging server in the middle to translate from websocket (browser) to udp / tcp protocols, in this sense you are right that it might not work as you planned it.

But it also looks like csound offers a websocket library (http://www.csounds.com/manual/html/websocket.html), maybe you try using this one to talk to the browser?

**Comment by gilfuser** [comment]
Hi.
For the about the same reasons than @jarmitage I'm trying to implement osc-js in an node.js app, and I'm getting the same results.
I'm trying to build an app using Webrtc with which people can get and send streams of OSC to use with SuperCollider, Pd, OpenFrameworks, etc.

I haven't linked the osc part with the webrtc, which is working. 
When I test it locally the OSC msgs go fine between the browser and SC, but when I deploy the app I get the same errors from jarmitage, both in Firefox and Chrome.
I tried to use the options like so in the node server.js:
```
const oscoptions = {
  receiver: 'ws', // @param {string} Where messages sent via 'send' method will be delivered to, 'ws' for Websocket clients, 'udp' for udp client
  udpServer: { port: 54321 },
  udpClient: { port: 57120 },
  wsServer: {
    host: '0.0.0.0', // @param {string} Hostname of WebSocket server
    port: 8080, // @param {number} Port of WebSocket server
  },
};
const osc = new OSC({ plugin: new OSC.BridgePlugin(oscoptions) });
osc.on('/hello', (message) => {
  console.log(message.args);
});
osc.open(); // start a WebSocket server on port 8080
```
and so in the app itself:
```
const options = {
  udpServer: { port: 54321 },
  udpClient: { port: 57120 },
  wsServer: {
    host: '0.0.0.0', // @param {string} Hostname of WebSocket server
    port: 8080, // @param {number} Port of WebSocket server
  },
  wsClient: {
    host: '0.0.0.0',
    port: 8080,
  },
};

let osc = new OSC(options);
osc.open(); // connect by default to ws://localhost:8080

document.getElementById('send-osc').addEventListener('click', () => {
  let message = new OSC.Message('/test/random', Math.random());
  osc.send(message);
});
```
I'm doing it from home, so there is no firewall-fancy-stuff here.
If there is any information I could give to circumvent what is causing the problem, please let me know.

best regards,
Gil
