### ISSUE TITLE
cannot replicate the example for getting messages from browser to Pure Data through node

### ISSUE THREAD

**Issue by adowty** [adzialocha/osc-js#27]
Im attempting to replicate the bridge html websocket- to node server- to pure data [netreceive] from the wiki.
html code:
```
<html>
<head>
<title>websockets udp bridge TEST</title>
<script src="lib/osc-js-master/lib/osc.min.js"></script>
</head>
<body>
<button id="send">Send Message</button>
<script type="text/javascript">
  var osc = new OSC();
  osc.open(); // connect by default to ws://localhost:8080
  document.getElementById('send').addEventListener('click', function() {
    var message = new OSC.Message('/test/random', Math.random());
    osc.send(message);
  });
</script>
</body>
</html>
 
```
server js:
```
var express = require('express');
// request allows us to make http requests to external apis
var request = require('request');
var path = require('path');
var fs = require('fs');
var ws = require('ws');

var app = express();
// load up web files with express
app.use(express.static(__dirname + '/views'));
app.use('/lib', express.static(__dirname + '/lib'));
app.use('/images', express.static(__dirname + '/images'));

// tell our node app to open its ears
var server = app.listen(8080, function() {
  console.log('listening at localhost:8080');
})

const OSC = require('osc-js')

const config = { udpClient: { port: 9129 } }
const osc = new OSC({ plugin: new OSC.BridgePlugin(config) })

osc.open() // start a WebSocket server on port 8080
```
PD vanilla patch is a simple:
[listen 9129]message
|
[netreceive -u -b]
|
[print]

console messages are:
WebSocket connection to 'ws://localhost:8080/' failed: Connection closed before receiving a handshake response
WebSocket is already in CLOSING or CLOSED state.

Actually, I noticed (as writing this post) that the html in your example in the wiki requires osc.min.js, (which I had to go get from the osc.js repository {not osc-js}) but i was using osc.browser.js to get these errors. When I switched it to requiring osc.min.js, I get:
Uncaught ReferenceError: OSC is not defined
(the link to the library file works fine)

osx and chrome, btw.
I'm sure I'm missing something silly.

**Comment by adowty351** [comment]
I think I got it.

**Comment by adowty351** [comment]
never mind

**Comment by niksigouin** [comment]
How did you resolve your problem?
