### ISSUE TITLE
Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

### ISSUE THREAD

**Issue by prafulsurve** [adzialocha/osc-js#29]
I am using bridge plugin to send a stream of data from the client to maxmsp. My server code is as follows-

```
const OSC = require('osc-js')

const config = { udpClient: { port: 8080 } }
const osc = new OSC({ plugin: new OSC.BridgePlugin(config) })

osc.open(); // start a WebSocket server on port 8080

osc.on('/imagecolors', (message) => {
  console.log(message);
})
```

And my client code is as follow-
```
(function(window) {
  var App = window.App || {};
  var colorlist = App.colorlist;
  var osc = new OSC();
  osc.open(); // connect by default to ws://localhost:8080
  for (var i = 0; i < colorlist.length; i++) {
    var message = new OSC.Message('/imagecolors', colorlist[i]);
    osc.send(message);
  }
})(window);

```

While sending the data I get an error message saying websocket still in connecting. I tried debugging the code at `osc.send() `the osc.status is `STILL_CONNECTING`.

**Comment by adzialocha** [comment]
It looks like you are using the same port for both WebSocket and UDP protocol (8080 is set by default for WebSocket, you set the UDP client to `8080` in the configuration).

**Comment by prafulsurve** [comment]
I changed the UDP client to some other port and it works perfectly fine. Thank you.
