### ISSUE TITLE
Having trouble using the bridge plug-in

### ISSUE THREAD

**Issue by ManjitBedi** [adzialocha/osc-js#34]
Hi.

I am working on a project using Touch Designer & we want to send data using OSC from a Node.js app.

I am getting the following error at run-time when trying to use the bridge plug-in:

```
"Error: BridgePlugin can not be used in browser context"
	BridgePlugin
osc.js:1073
require<[5]<
camera_osc.js:34:30
newRequire
http://localhost:1234/dist/904f316f53e694a9253efea39d6a5f51.js:42:7
require<
http://localhost:1234/dist/904f316f53e694a9253efea39d6a5f51.js:69:5
<anonymous>
http://localhost:1234/dist/904f316f53e694a9253efea39d6a5f51.js:10:12

```

**Comment by adzialocha** [comment]
@ManjitBedi How do you use the library in your code? Do you use the `BridgePlugin` on the client-side? Its only meant to be used on the server-side, the client would make use of the default `WebsocketClientPlugin`.

**Comment by ManjitBedi** [comment]
We are using UDP with Touch Designer.   I have tested sending UDP packets with other apps & it is working.  I changed the code to the following based on the Wiki page.  

```
const dgram = require('dgram')
const OSC = require('osc-js')

const options = {
  send: {
      host: '127.0.0.1',   // @param {string} Hostname of udp client for messaging
      port: 3333           // @param {number} Port of udp client for messaging
    }
}

const osc = new OSC({ plugin: new OSC.DatagramPlugin(options) })
osc.open()

// send a messsage via udp
osc.send(new OSC.Message('/test'))
```

I now get a different error:

```
TypeError: dgram.createSocket is not a function[Learn More] osc.js:973
DatagramPlugin
osc.js:973
require<[7]<
camera_osc.js:39:30
newRequire
http://localhost:1234/dist/904f316f53e694a9253efea39d6a5f51.js:42:7
require<
http://localhost:1234/dist/904f316f53e694a9253efea39d6a5f51.js:69:5
<anonymous>
http://localhost:1234/dist/904f316f53e694a9253efea39d6a5f51.js:10:12
```

**Comment by ManjitBedi** [comment]
I see that UDP is not possible with Javascript in a browser app.

**Comment by adzialocha** [comment]
@ManjitBedi Yes! You will need to have a middleman between the browser and your UDP server application. This could be a Node.JS server for example, here is something: https://github.com/adzialocha/osc-js/wiki/PureData-&-MaxMSP

**Comment by ManjitBedi** [comment]
I see;  I get what you are saying;  thanks for the suggestion.
