### ISSUE TITLE
Configuration for using https with web sockets?

### ISSUE THREAD

**Issue by ManjitBedi** [adzialocha/osc-js#36]
Hi.

We have been using your library for weeks;  it has been great. Now, we want to be able to use https;  this is because we want the web browser to remember the user's web cameras choice.  We have osc-js working with the Google PoseNet demo.  We are seeing the connection fail when trying to see wss.

```
Firefox can’t establish a connection to the server at wss://localhost:8080/.
```

I have set up the code using yarn & parcel based on the original demo code, from the package.json:

```
  "scripts": {
    "secure": "NODE_ENV=development parcel --no-hmr --open camera2.html --https",
  },
```

here is the code in the app that sends the data using the bridge:
```
let osc = new OSC();
osc.open({secure: true});
```

An example message: 
```
    // Right Shoulder
    let message9 = new OSC.Message(messageRightWrist, keypoints[10].position.x,
      keypoints[10].position.y);

    osc.send(message9);
```

And here is the bridge server code:
```
const OSC = require('osc-js');
const chalk = require('chalk');
const log = console.log;


// This port value is the receiver port for the touch designer project
const sendingPort = 3333;
const receivingPort = 3334;

// Using default values for everything else with the configuration.
const config = {
  wsServer: {
    secure: true
  },
  udpServer: {
   port: receivingPort,   // @param {number} Port of udp server to bind to
   exclusive: false       // @param {boolean} Exclusive flag
  },
  udpClient: {
    port: sendingPort,
    exclusive: false
  }
};

const osc = new OSC({ plugin: new OSC.BridgePlugin(config) });

osc.open() // start a WebSocket server on port 8080

log(chalk.underline("OSC Bridge server running"));
log("Web Socket - listening on port: " + chalk.green('8080'));
log("UDP - sending on port: " + chalk.green(sendingPort));
log("UDP - receiving on port: " + chalk.green(receivingPort));

osc.on('/posenet', message => {
  // Send the posenet OSC message to the Posenet Node.js app.
  osc.send(message);
})
```

**Comment by adzialocha** [comment]
Hi @ManjitBedi! Did you use a self-signed certificate and added an exception manually before? Maybe this helps you: https://bugzilla.mozilla.org/show_bug.cgi?id=1187666. If this is still not working, I will look more into this.

**Comment by ManjitBedi** [comment]
Hi @adzialocha ,  I am actually spending time doing more work on the project that is using OSC  in the coming week.  I will review the set-up & get back you.

**Comment by ManjitBedi** [comment]
Hello,  apologies for the delay in getting back to you.  Yes, I did create a self signed certificate.  I will make a note to test it again later this week.

**Comment by ManjitBedi** [comment]
I just spent some on this;  I cannot get the self signing certificate to work with Node.js & yarn etc.  This is not your problem but an issue for the people I work with.  We may come back to this in future.  For now, we can close this issue.  Thanks again for the super useful OSC code.

**Comment by adzialocha** [comment]
Thank you for getting back @ManjitBedi!
