### ISSUE TITLE
Closing tab stops the server

### ISSUE THREAD

**Issue by luisArandas** [adzialocha/osc-js#38]
I am implementing OSC.js in my server for external communications and to send data from my page but everytime I close a tab all the server goes down.
Error is:

```
events.js:167

      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at WebSocket.finalize (/Users/luisarandas/Desktop/GitHub/akson/node_modules/ws/lib/WebSocket.js:182:41)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Any help on this?
Best, Luis

**Comment by adzialocha** [comment]
Hi @luisArandas! It might help to disconnect before the tab is closed. You can do this by using the `onbeforeunload` event of the `window` object. For example:

```js
window.onbeforeunload = () => {
  osc.close();
};
```

Another example (React, Redux) here: https://github.com/adzialocha/kubismus/blob/master/src/scripts/index.js#L15

**Comment by luisArandas** [comment]
Hello adzialocha and thank you for your kind response.
I ran into another problem, I'm building a heroku server app with node.js but I don't seem to be able to open more ports than the one the app is serving.
I am not able to implement this by sockets in my app. Everytime I test osc.js it denies and closes the socket. My point would be to connect to pure data or maxmsp, any help on this?
Best, Luis
