### ISSUE TITLE
Can't send message with value of 0

### ISSUE THREAD

**Issue by maxjoehnk** [adzialocha/osc-js#4]
```
    if (!this.value) {
      throw new Error('OSC Atomic cant\'t be encoded with empty value')
    }
```

This check throws when there are falsy values (like 0).
This should either check for null or undefined values which would also allow empty strings or maybe use a separate function like `isEmpty(value): boolean` which can be overridden.

What do you think? I can create a pull request with a fix if you want.

**Comment by adzialocha** [comment]
@maxjoehnk thank you for spotting this! I added a test to check against these cases and fixed the problem with an own helper method as you suggested.

**Comment by maxjoehnk** [comment]
Thanks. Did you forget to push it to npm? Because version 1.0.2 isn't up yet

**Comment by adzialocha** [comment]
It should be up: https://www.npmjs.com/package/osc-js
