### ISSUE TITLE
Connect to PD or Max MSP

### ISSUE THREAD

**Issue by adzialocha** [adzialocha/osc-js#40]
I ran into another problem, I'm building a heroku server app with node.js but I don't seem to be able to open more ports than the one the app is serving.
I am not able to implement this by sockets in my app. Everytime I test osc.js it denies and closes the socket. My point would be to connect to pure data or maxmsp, any help on this?
Best, Luis

_Originally posted by @luisArandas in https://github.com/adzialocha/osc-js/issues/38#issuecomment-471327242_

**Comment by adzialocha** [comment]
I'm not really sure what exactly you are trying to achieve @luisArandas / what your setup is, but did you have a look at this example: https://github.com/adzialocha/osc-js/wiki/PureData-&-MaxMSP

**Comment by luisArandas** [comment]
Thank you for the response adzialocha. Yes, that works locally. Not when I upload to the server.
Any insight on this?

**Comment by phishchiang** [comment]
Same here, it works fine locally but can't properly run after deploy to the Heroku and the error message is 'WebSocket is already in CLOSING or CLOSED state.'

**Comment by TyIsI** [comment]
@luisArandas Unfortunately, Heroku doesn't support multiple ports. For the 'web' types, it just supports a HTTP port.

See more on https://stackoverflow.com/a/37645044/4313368

**Comment by adzialocha** [comment]
Thank you @TyIsI for clearing that up!
