### ISSUE TITLE
Uncaught ReferenceError: OSC is not defined

### ISSUE THREAD

**Issue by dblanchemain** [adzialocha/osc-js#45]
```
<!DOCTYPE html>
<html>
    <head>
        <title>osc.js Web Sockets</title>
        <meta charset="UTF-8" />
        <script t type="text/javascript"  src="osc.js"></script>      
    </head>
    <body>
    <button id="send"> Test</button>
		<script type="text/javascript">

		const osc1 = new OSC();
		osc1.open({host:localhost, port:3819});
  		document.getElementById('send').addEventListener('click', () => {
   	var message = new OSC.Message('/strip/list');
    	osc1.send(message);
  });
</script> 
    </body>
</html>
```

I am unable to send an osc message to Ardour (DAW localhost port: 3819). I still have an error message: with the OSC object :  OSC is not defined (with chrome).

**Comment by adzialocha** [comment]
Hi @dblanchemain!

How do you host the `osc.js` file on your HTTP server? I assume its not served properly as your code looks alright.

Also I can see a typo in `<script ..` (there is a `t`), maybe this already solves the issue?
