### ISSUE TITLE
Browser(http) osc message to Reaper(udp)

### ISSUE THREAD

**Issue by dblanchemain** [adzialocha/osc-js#53]
I don't get it. I just want to send osc messages from a browser (**Firefox or Chrome**) to DAW **Reaper** sur son port **UDP** in order to control settings.  I do it with another application in c++ and it works.
I wrote this code:

```
<!DOCTYPE html>
<html>
    <head>
        <title>osc.js Web Sockets</title>
        <meta charset="UTF-8" />
      <script type="text/javascript" src="osc.js"></script>
       <script type="text/javascript" src="osc-browser-min.js"></script>
        
    </head>
    <body>
	 <button id="send">Send Message</button>
	
	<script type="text/javascript">
	 
	 const  config  =  {  udpClient: {host:'127.0.0.1',  port:9001  }  } 
 	 var osc = new OSC({plugin : new  OSC.BridgePlugin (config)  } );
 	 osc.open(); 
//console.log("Bridge listening as Server:: Host: " + osc.server.host + ", Port: " + osc.client.port);
  	 document.getElementById('send').addEventListener('click', () => {
    var message = new OSC.Message('/track/2/*',  Math.random());
    osc.send(message);
  });
</script>
    </body>
</html>
```

```
Uncaught ReferenceError: OSC is not defined
    <anonymous> http://localhost/OSC/oscsend.html:15
```

What is not correct? 
What are the .js files that need to be loaded into the html page for this to work?
I'm not sure about the procedure either, can you tell me if this would be suitable?
It's a bit hopeless!

**Comment by adzialocha** [comment]
Hi @dblanchemain! :wave: 

I assume you're hosting all of these files statically via HTTP? Are all files in the same folder you serve from? Can you see something missing (404 Error) in the Network tab of your developer inspector in your browser?

You would only need to use the `osc-browser-min.js` version, not `osc.js`. In osc-js the file is actually named `osc.browser.min.js` and you find it in the `lib` folder (see example [here](https://github.com/adzialocha/osc-js#example-osc-between-maxmsppdsc-etc-and-your-browser)), but I assume you've renamed it?

**Comment by adzialocha** [comment]
Also, I'm just noting that you're using the `BridgePlugin` in the browser which is not possible since browsers do not have the option to make udp requests.

What you would like to do here is to send your OSC via WebSocket to a host which is capable of understanding WebSocket and then translating the request further UDP to then pass it further, this is exactly what the `BridgePlugin` does, but it would need to live somewhere outside of the browser (for example running as a NodeJS application). Again, check out https://github.com/adzialocha/osc-js#example-osc-between-maxmsppdsc-etc-and-your-browser!

**Comment by Enigma644** [comment]
FYI, there is no lib folder in the repo.
I note that in your gitignore, you have "lib" listed to not be included.

**Comment by adzialocha** [comment]
> FYI, there is no lib folder in the repo.
> I note that in your gitignore, you have "lib" listed to not be included.

It is included in builds which are published on npm. If you install the library via `npm i osc-js` it will include the build for you in the `lib` folder.

If you prefer to make the build yourself you need to clone the repository and follow the development steps in the `README.md` (`npm install` and `npm run build`)
