### ISSUE TITLE
Use TypeScript

### ISSUE THREAD

**Issue by adzialocha** [adzialocha/osc-js#55]

**Comment by Polyterative** [comment]
lacking typescript support is what blocks me from doing the work I need. Even basic support would help.

**Comment by adzialocha** [comment]
> lacking typescript support is what blocks me from doing the work I need. Even basic support would help. 

Any contribution in this direction is welcome 👍

**Comment by JacobMuchow** [comment]
In the meantime, or in case that is closed, I made some (mostly complete) custom typings anyone can use.

I didn't bother with getting the OSC.open({ }) options to work depending on which plugin you were using, but you could probably do some generics for that.

https://gist.github.com/JacobMuchow/79b3cc7014ec869dff0c4dd83a2aaf34

**Comment by adzialocha** [comment]
TypeScript support got merged now and released with version `2.4.0` :sparkler: Thank you @JacobMuchow !!
