### ISSUE TITLE
Integer bundle timetags ignored

### ISSUE THREAD

**Issue by yaxu** [adzialocha/osc-js#60]
Hi, I'm having trouble getting a timestamped bundle through BridgePlugin.

I send the bundle like this, to timestamp it 5 seconds into the future:
```html
<button id="send" style="font-size: 2em">Send bundle</button>
<script type="text/javascript" src="./node_modules/osc-js/lib/osc.min.js"></script>
<script type="text/javascript">
  const comm = new OSC();
  comm.open(); // connect by default to ws://localhost:8080
  document.getElementById('send').addEventListener('click', function () {
    const message = new OSC.Message(
      '/dirt/play',
      ...['s', 'hh'],
    );
    const bundle = new OSC.Bundle([message], Date.now() + 5000)
    comm.send(bundle);
  });
</script>
```
This goes through the bridge:
```javascript
const OSC = require('osc-js');

const config = {
  receiver: 'ws', 
  udpServer: {
    host: 'localhost', 
    port: 57121,
    exclusive: false,
  },
  udpClient: {
    host: 'localhost',
    port: 57120, 
  },
  wsServer: {
    host: 'localhost',
    port: 8080,
  },
};

const osc = new OSC({ plugin: new OSC.BridgePlugin(config) });
osc.open();
```
Sniffing the UDP with wireshark though, I can see that the OSC that comes out has a timestamp of 'now' rather than 'now-plus-5-seconds'.

Could there be something wrong in the BridgePlugin, or am I constructing the bundle wrong in the first place? Any help would be much appreciated!

**Comment by yaxu** [comment]
I think I found the bug:
https://github.com/adzialocha/osc-js/blob/d5693c6cc4013fe39658a233ca37f44ff3e4b03a/src/bundle.js#L55
`isInt(args[0])` should be `isInt(args[1])`.

Currently:
* this doesn't work: `bundle = new OSC.Bundle([message], Date.now() + 5000)`
* this does: `bundle = new OSC.Bundle(Date.now() + 5000, message)`

**Comment by adzialocha** [comment]
> Correction - `bundle = new OSC.Bundle(Date.now() + 5000, message)` has the right timestamp, but the message doesn't get added.
> The PR fixes `bundle = new OSC.Bundle([message], Date.now() + 5000)`, in any case.

Amazing! Thanks for spotting this @yaxu! Another reason to slowly look into porting this project to Typescript 😅
