### ISSUE TITLE
[UDP] open() overrides initial options

### ISSUE THREAD

**Issue by davidgranstrom** [adzialocha/osc-js#9]
Hi,

I'm trying out the UDP plugin and I found that calling open() without options actually seem to override the options passed to the constructor. The code below demonstrates the issue, comment out `osc.open({ port: PORT });` and it should receive the `/test` message on port 9912. Its easy to solve as seen below, thought I should report it here just so you'd know about it! :)

```
const OSC = require('osc-js');
const PORT = 9912;
const options = {
  open: {
    host: 'localhost',
    port: PORT
  }
};
const osc = new OSC({ plugin: new OSC.DatagramPlugin(options) });

osc.on('test', (message) => {
  console.log('message.args', message.args);
});

// osc.open({ port: PORT });
osc.open();
```

**Comment by adzialocha** [comment]
This is fixed now via https://github.com/adzialocha/osc-js/pull/14

**Comment by adzialocha** [comment]
https://github.com/adzialocha/osc-js/releases/tag/1.0.4
